config/routes.rb
RailsExercise::Application.routes.draw do

  post 'progress_bars/show/:id', as: 'progress_bar', to: 'progress_bars#show'
  
  post "search_results/show", as: 'show'

  post "search_results/searching", as: 'searching'

  get 'index', to: 'landing#index'

  root 'landing#index'

  

end

app/models/flight.rb
class Flight < ActiveRecord::Base
end

app/models/progress_bar.rb
class ProgressBar < ActiveRecord::Base
  validates_presence_of :message
  validates_numericality_of :percent,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 100
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/job_queue.rb
require 'thread'
module JobQueue
  extend ActiveSupport::Concern

  private
  def find_queue
    @queue = @queue || Queue.new
    Thread.new do
      while current_progress_bar = @queue.pop(false)
        current_progress_bar.update_attributes!({
          message: 'Working ...',
          percent: 0
        })
        
        20.times do |i|
          sleep(1)
          current_progress_bar.update_attributes!(percent: i * 5)
        end
        
        current_progress_bar.update_attributes!({
          message: 'Finished!',
          percent: 100
        })
      end
      ActiveRecord::Base.connection.close
    end
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render action: 'show', status: :created, location: @flight }
      else
        format.html { render action: 'new' }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:from, :to, :date_of_journey, :dep_time, :arr_time, :price)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/progress_bars_controller.rb
class ProgressBarsController < ApplicationController
  before_action :set_progress_bar, only: [:show, :edit, :update, :destroy]

  # GET /progress_bars
  # GET /progress_bars.json
  def index
    @progress_bars = ProgressBar.all
  end

  # GET /progress_bars/1
  # GET /progress_bars/1.json
  def show
    @progress_bar = ProgressBar.find(params[:id])
    render json: @progress_bar
  end

  # GET /progress_bars/new
  def new
    @progress_bar = ProgressBar.new
  end

  # GET /progress_bars/1/edit
  def edit
  end

  # POST /progress_bars
  # POST /progress_bars.json
  def create
    @progress_bar = ProgressBar.new(progress_bar_params)

    respond_to do |format|
      if @progress_bar.save
        format.html { redirect_to @progress_bar, notice: 'Progress bar was successfully created.' }
        format.json { render action: 'show', status: :created, location: @progress_bar }
      else
        format.html { render action: 'new' }
        format.json { render json: @progress_bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /progress_bars/1
  # PATCH/PUT /progress_bars/1.json
  def update
    respond_to do |format|
      if @progress_bar.update(progress_bar_params)
        format.html { redirect_to @progress_bar, notice: 'Progress bar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @progress_bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progress_bars/1
  # DELETE /progress_bars/1.json
  def destroy
    @progress_bar.destroy
    respond_to do |format|
      format.html { redirect_to progress_bars_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progress_bar
      @progress_bar = ProgressBar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def progress_bar_params
      params.require(:progress_bar).permit(:message, :percent)
    end
end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController
  include JobQueue
  before_action :find_queue, only: :searching
  
  def show
    @result = Flight.all[session[:progress_id]]
  end

  def searching
    @progress_bar = ProgressBar.create!(message: 'Queued', percent: 0)
    session[:search_params] = params
    session[:progress_id] = @progress_bar.id
    @queue.push(@progress_bar)
    respond_to do |format|
      format.js
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/progress_bars_helper.rb
module ProgressBarsHelper
end

app/helpers/search_results_helper.rb
module SearchResultsHelper
end

app/views/flights/_flight.html.erb
<div>
    <div>From: <%= flight.from %></div>
    <div>To: <%= flight.to %></div>
    <div>Departure: <%= flight.dep_time %></div>
    <div>Arrival: <%= flight.arr_time %></div>
    <div>Date: <%= flight.date_of_journey %></div>
    <div>Price: Rs.<%= flight.price %></div>
</div>

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br>
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :to %><br>
    <%= f.text_field :to %>
  </div>
  <div class="field">
    <%= f.label :date_of_journey %><br>
    <%= f.date_select :date_of_journey %>
  </div>
  <div class="field">
    <%= f.label :dep_time %><br>
    <%= f.time_select :dep_time %>
  </div>
  <div class="field">
    <%= f.label :arr_time %><br>
    <%= f.time_select :arr_time %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<h1>Listing flights</h1>

<table>
  <thead>
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Date of journey</th>
      <th>Dep time</th>
      <th>Arr time</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.from %></td>
        <td><%= flight.to %></td>
        <td><%= flight.date_of_journey %></td>
        <td><%= flight.dep_time %></td>
        <td><%= flight.arr_time %></td>
        <td><%= flight.price %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<h1>New flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @flight.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @flight.to %>
</p>

<p>
  <strong>Date of journey:</strong>
  <%= @flight.date_of_journey %>
</p>

<p>
  <strong>Dep time:</strong>
  <%= @flight.dep_time %>
</p>

<p>
  <strong>Arr time:</strong>
  <%= @flight.arr_time %>
</p>

<p>
  <strong>Price:</strong>
  <%= @flight.price %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

app/views/landing/index.html.erb
<%= form_tag searching_path, method: :post, class: 'form' do %>
    <div class='form-group'>
    <%= label_tag :from %>
    <%= select_tag :from, options_for_select(["", "A", "B", "C"], ""), class: 'form-control' %>
    </div>
    <div class='form-group'>
    <%= label_tag :to %>
    <%= select_tag :to, options_for_select(["", "A", "B", "C"], ""), class: 'form-control' %>
    </div>
    <div class='form-group'>
    <%= label_tag :date %>
    <div class="input-group date">
      <input type="text" class="form-control" id="date" name="date"><span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
    </div>
    </div>
    <div class='form-group'>
    <%= radio_button_tag :path, 1, class: 'form-control' %>One way
    <%= radio_button_tag :path, 2, class: 'form-control' %>Two way
    </div>
    <div class='form-group'>
    <%= submit_tag 'Search', class: 'btn btn-primary' %>
    </div>
<% end %>
<script>
      $('.input-group.date').datepicker({
        startDate: "today",
        clearBtn: true,
        autoclose: true,
        todayHighlight: true
      });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsExercise</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/progress_bars/_form.html.erb
<%= form_for(@progress_bar) do |f| %>
  <% if @progress_bar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@progress_bar.errors.count, "error") %> prohibited this progress_bar from being saved:</h2>

      <ul>
      <% @progress_bar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :percent %><br>
    <%= f.text_field :percent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/progress_bars/edit.html.erb
<h1>Editing progress_bar</h1>

<%= render 'form' %>

<%= link_to 'Show', @progress_bar %> |
<%= link_to 'Back', progress_bars_path %>

app/views/progress_bars/index.html.erb
<h1>Listing progress_bars</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>Percent</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @progress_bars.each do |progress_bar| %>
      <tr>
        <td><%= progress_bar.message %></td>
        <td><%= progress_bar.percent %></td>
        <td><%= link_to 'Show', progress_bar %></td>
        <td><%= link_to 'Edit', edit_progress_bar_path(progress_bar) %></td>
        <td><%= link_to 'Destroy', progress_bar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Progress bar', new_progress_bar_path %>

app/views/progress_bars/new.html.erb
<h1>New progress_bar</h1>

<%= render 'form' %>

<%= link_to 'Back', progress_bars_path %>

app/views/progress_bars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @progress_bar.message %>
</p>

<p>
  <strong>Percent:</strong>
  <%= @progress_bar.percent %>
</p>

<%= link_to 'Edit', edit_progress_bar_path(@progress_bar) %> |
<%= link_to 'Back', progress_bars_path %>

app/views/search_results/_show.html.erb
<%= render @result %>
<%= button_to 'Back', index_path, method: :get, class: 'btn btn-warning' %>

app/views/search_results/searching.html.erb
<div class="container">
  <div id="bar" class="progress" data-ping-time="1000">
    <div class="progress-bar progress-bar-info" style="width: 0%;">
      0%
    </div>
  </div>
</div>
<script type="text/javascript">
  <%= (render partial:'searching.js') %>
</script>

app/views/search_results/show.html.erb
<%= render @result %>
<%= button_to 'Back', index_path, method: :get %>

app/views/search_results/show.js.erb
$('body').html("<%= j (render partial: 'show') %>")